name: test

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
    tags:
      - "v*"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, 14, 15, 16]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-1-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

      - run: yarn
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: yarn build
